/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnotherDivContainerComponent: typeof import('./src/components/deprecated/anotherDivContainerComponent.vue')['default']
    BackgroundComponent: typeof import('./src/components/deprecated/backgroundComponent.vue')['default']
    EmptyComponent: typeof import('./src/components/emptyComponent.vue')['default']
    MainNuxtUi: typeof import('./src/components/MainNuxtUi.vue')['default']
    MvpComponentVue: typeof import('./src/components/deprecated/mvpComponentVue.vue')['default']
    NewFetchComponentVue: typeof import('./src/components/deprecated/newFetchComponentVue.vue')['default']
    NewFileComponent: typeof import('./src/components/deprecated/newFileComponent.vue')['default']
    NonAnimatedMeshGradientBackground: typeof import('./src/components/deprecated/nonAnimatedMeshGradientBackground.vue')['default']
    PicoCssSimpleComponent: typeof import('./src/components/deprecated/picoCssSimpleComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAccordion: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UContainer: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UInputMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue')['default']
    ULinkBase: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
  }
}
